### PR TITLE
Fix method description

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Review by mthadley — APPROVED** [review]
@fernandosouza Very nice! `<a>` without an `href` was definitely not very semantic or accessible. LGTM!

We have some accessibility work to do on some of the other components as well. (Looking at you, `metal-dropdown`).

**Review by robframpton — APPROVED** [review]
LGTM

**Review by brunobasto — APPROVED** [review]
LGTM

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/metal/metal-tabs/compare/000dcea~0...000dcea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
